version: '3.5'
services:
    jenkins:
        # image: jenkinsci/blueocean:1.5.0
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - $HOME/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        healthcheck:
            test: ["CMD", "curl", "-f",
                "http://localhost:8080/login"]
            interval: 10m
            timeout: 10s
            retries: 3
            start_period: 5m
        restart: always
